### ISSUE TITLE
Potential Icons

### ISSUE THREAD

**Issue by ApolloZhu** [CaptainYukinoshitaHachiman/iOS-Dev-Stickers#1]
Prototype:
![f6174ed8-7ec5-4e00-9462-4ad59c64dd15](https://user-images.githubusercontent.com/10842684/31079407-8d37dc8e-a753-11e7-9621-a363c3909c2b.jpeg)

**Comment by ApolloZhu** [comment]
How about this? @CaptainYukinoshitaHachiman 
![image](https://user-images.githubusercontent.com/10842684/31084490-8a2dff8c-a762-11e7-9639-11ee9c7ae9a5.png)

**Comment by uetcis** [comment]
wow, this seems nice
I'll change the icon into it soon
